- name: start marathon xcache redirector
  run_once: true
  uri:
    url: "{{marathon_protocol}}://marathon.service.consul:{{marathon_port}}/v2/apps/xcacheredir"
    user: "{{marathon_username}}"
    password: "{{marathon_password}}"
    validate_certs: "no"
    method: PUT
    HEADER_Content-Type: "application/json"
    body: "{{ lookup('template', 'templates/Marathon/redirector.json') }}"
    body_format: json
  register: result
  until: result.status == 200
  retries: 10
  delay: 20
  changed_when: false

- name: start marathon xcache server
  run_once: true
  uri:
    url: "{{marathon_protocol}}://marathon.service.consul:{{marathon_port}}/v2/apps/xcacheserver"
    user: "{{marathon_username}}"
    password: "{{marathon_password}}"
    validate_certs: "no"
    method: PUT
    HEADER_Content-Type: "application/json"
    body: "{{ lookup('template', 'templates/Marathon/server.json') }}"
    body_format: json
  register: result
  until: result.status == 200
  retries: 10
  delay: 20
  changed_when: false

- name: start marathon xcache exposer
  run_once: true
  uri:
    url: "{{marathon_protocol}}://marathon.service.consul:{{marathon_port}}/v2/apps/expose"
    user: "{{marathon_username}}"
    password: "{{marathon_password}}"
    validate_certs: "no"
    method: PUT
    HEADER_Content-Type: "application/json"
    body: "{{ lookup('template', 'templates/Marathon/proxy.json') }}"
    body_format: json
  register: result
  until: result.status == 200
  retries: 10
  delay: 20
  changed_when: false