
---
kind: Service
apiVersion: v1
metadata:
  name: xcache-service
spec:
  type: NodePort
  selector:
    app: xredir
  ports:
  - protocol: TCP
    name: xrootd
    port: 1094
    targetPort: 1094
    nodePort: 31094
  - protocol: TCP
    name: cmsd
    port: 31213
    targetPort: 31213
    nodePort: 31213
---
kind: Service
apiVersion: v1
metadata:
  name: xcache-proxy
spec:
  type: NodePort
  selector:
    app: proxy
  ports:
  - protocol: TCP
    name: xrootd
    port: 1194
    targetPort: 1194
    nodePort: 31194
  externalIPs:
  - "{{ master_ip }}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xredir-pod
  labels:
    app: xredir
spec:
  template:
    metadata:
      labels:
        app: xredir
    spec:
      containers:
      - name: redirector
        imagePullPolicy: Always
        args:
        - --nogrid
        - --redirector
        - --health_port
        - "8080"
        env:
        - name: REDIR_CMSD_PORT
          value: "31213"
        - name: REDIR_HOST
          value: xcache-service.default.svc.cluster.local 
        - name: REDIR_XRD_PORT
          value: "1094"
        image: cloudpg/xrootd-proxy:cms
        livenessProbe:
          exec:
            command:
            - curl
            - -f
            - http://localhost:8080/check_health
        ports:
        - containerPort: 1094
        - containerPort: 31213

  selector:
    matchLabels:
      app: xredir

  replicas: 1

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-pod
  labels:
    app: proxy
spec:
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
      - name: proxy
        imagePullPolicy: Always
        args:
        - --nogrid
        - --expose
        - --health_port
        - "8080"
        env:
        - name: REDIR_HOST
          value: xcache-service.default.svc.cluster.local
        - name: REDIR_XRD_PORT
          value: "1094"
        image: cloudpg/xrootd-proxy:cms
        ports:
        - containerPort: 1194

  selector:
    matchLabels:
      app: proxy

  replicas: 1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xcache-pod
  labels:
    app: xcache
spec:
  template:
    metadata:
      labels:
        app: xcache
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - xcache
            topologyKey: "kubernetes.io/hostname"
      volumes:
      - name: xcache-data
        hostPath:
          path: /data/xrd
      - name: xcache-creds
        hostPath:
          path: /tmp 
      containers:
      - name: cache
        imagePullPolicy: Always
        args:
        - --proxy
        - --health_port
        - "8088"
        env:
        - name: BLOCK_SIZE
          value: "{{ BLOCK_SIZE }}"
        - name: CACHE_LOG_LEVEL
          value: "{{ CACHE_LOG_LEVEL }}"
        - name: CACHE_PATH
          value: /data/xrd
        - name: CACHE_RAM_GB
          value: "{{ CACHE_RAM_GB }}"
        - name: HI_WM
          value: "{{ HI_WM }}"
        - name: LOW_WM
          value: "{{ LOW_WM }}"
        - name: N_PREFETCH
          value: "{{ N_PREFETCH }}"
        - name: ORIGIN_HOST
          value: "{{ ORIGIN_HOST }}"
        - name: ORIGIN_XRD_PORT
          value: "{{ ORIGIN_XRD_PORT }}"
        - name: REDIR_CMSD_PORT
          value: "31213"
        - name: REDIR_HOST
          value: xcache-service.default.svc.cluster.local
        - name: STREAMS
          value: "{{ STREAMS }}"
        image: cloudpg/xrootd-proxy:cms
        volumeMounts:
        - mountPath: /data/xrd
          name: xcache-data
        ## WAITING FOR CMS VOMS TTS solution
        # - mountPath: /tmp/
        #   name: xcache-creds
        livenessProbe:
          exec:
            command:
            - curl
            - -f
            - http://localhost:8088/check_health
          initialDelaySeconds: 300
          periodSeconds: 60
        ports:
        - containerPort: 32294
        - containerPort: 31113
      ## WAITING FOR CMS VOMS TTS solution
      # - name: proxy
      #   imagePullPolicy: Always
      #   image: cloudpg/get-proxy
      #   env:
      #   - name: PROXY_URL
      #     value: "{{ tts_url }}"
      #   - name: PROXY_token
      #     value: "{{ iam_token }}"
      #   volumeMounts:
      #   - mountPath: /tmp/
      #     name: xcache-creds
      #   livenessProbe:
      #     exec:
      #       command:
      #       - curl
      #       - -f
      #       - http://localhost:8888/check_health
      #     initialDelaySeconds: 300
      #     periodSeconds: 60

  selector:
    matchLabels:
      app: xcache

  replicas: 1
